version: '3.9'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ds-cluster-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
