name: GENESIS CSV Downloader

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-genesis-script:
    runs-on: ubuntu-latest

    env:
      GENESIS_USERNAME: ${{ secrets.GENESIS_USERNAME }}
      GENESIS_PASSWORD: ${{ secrets.GENESIS_PASSWORD }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ⚙️ Run GENESIS Download Script
        run: |
          python -c "import os, sys; sys.path.append(os.path.abspath('src')); from src.download_table_auto import download_and_extract_table_auto; from src.loader import load_genesis_csv; code = '48112-0002'; c_year = '2022'; csv_path = download_and_extract_table_auto(code, c_year, dest_folder='data/raw'); df = load_genesis_csv(csv_path, zip_name=code+'_'+c_year); print(df.head())"
